server:
  port: 9900
#  servlet:
#    context-path: /gateway
spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: user_service
#          uri: http://localhost:18082
          uri: lb://user-service
          predicates:
            - Path=/user/**
#          filters:
#            - StripPrefix=1
#      discovery:
#        locator:
#          enabled: true   # 是否自动识别服务发现标识

