version: '3'
services:
  mysql_master:
    image: mysql:8.0.30
    container_name: mysql_master
    hostname: mysql_master
    ports:
      - "3306:3306"
    volumes:
      - /Users/wangmaosong/workspace/data-middle-platform/deploy/docker-mysql/config/mysql_master:/etc/mysql/conf.d
      - /Users/wangmaosong/workspace/data-middle-platform/deploy/docker-mysql/data/mysql_master:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  mysql_slave01:
    image: mysql:8.0.30
    container_name: mysql_slave01
    hostname: mysql_slave01
    ports:
      - "3307:3306"
    volumes:
      - /Users/wangmaosong/workspace/data-middle-platform/deploy/docker-mysql/config/mysql_slave01:/etc/mysql/conf.d
      - /Users/wangmaosong/workspace/data-middle-platform/deploy/docker-mysql/data/mysql_slave01:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  mysql_slave02:
    image: mysql:8.0.30
    container_name: mysql_slave02
    hostname: mysql_slave02
    ports:
      - "3308:3306"
    volumes:
      - /Users/wangmaosong/workspace/data-middle-platform/deploy/docker-mysql/config/mysql_slave02:/etc/mysql/conf.d
      - /Users/wangmaosong/workspace/data-middle-platform/deploy/docker-mysql/data/mysql_slave02:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin