version: "3"
services:
  user:
    image: user:V1
    pull_policy: never
    ports:
      - 18081
    environment:
      - APP_INSTANCE=1
#    depends_on: mysql
#  mysql:
#    image: mysql:8.0.30-oracle
#    restart: unless-stopped
#    environment:
#      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#      - MYSQL_DATABASE=$MYSQLDB_DATABASE