spring:
  application:
    name: datasource
  profiles:
    active: local
  sql:
    init:
      continue-on-error: false
      schema-locations: classpath:db/init.sql
      data-locations: classpath:db/data.sql
  docker:
    compose:
      enabled: false
      file: datasource-service/docker-compose.yml
      lifecycle-management: start_and_stop
      start:
        log-level: info
        command: up
      stop:
        command: down
        timeout: 10s
      skip:
        in-tests: true
      host: 127.0.0.1
      readiness:
        tcp:
          connect-timeout: 200ms
          read-timeout: 200ms
        wait: always
        timeout: 2m


mybatis-plus:
  global-config:
    db-config:
      id-type: auto # ID 生成规则
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
