server:
  port: 8081

spring:
  application:
    name: eureka-service

eureka:
  server:
    # 是否开启自我保护机制
    enable-self-preservation: false
  instance:
    hostname: eureka-service
    prefer-ip-address: true
    instance-id: ${spring.application.name}
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false



logging:
  charset:
    console: utf-8
  config: classpath:logback-spring.xml
